// Code generated by go-swagger; DO NOT EDIT.

package presence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// GetPresenceReader is a Reader for the GetPresence structure.
type GetPresenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPresenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPresenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetPresenceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPresenceOK creates a GetPresenceOK with default headers values
func NewGetPresenceOK() *GetPresenceOK {
	return &GetPresenceOK{}
}

/*GetPresenceOK handles this case with default header values.

The presence state for this user.
*/
type GetPresenceOK struct {
	Payload *models.GetPresenceOKBody
}

func (o *GetPresenceOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/presence/{userId}/status][%d] getPresenceOK  %+v", 200, o.Payload)
}

func (o *GetPresenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPresenceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPresenceNotFound creates a GetPresenceNotFound with default headers values
func NewGetPresenceNotFound() *GetPresenceNotFound {
	return &GetPresenceNotFound{}
}

/*GetPresenceNotFound handles this case with default header values.

There is no presence state for this user. This user may not exist or
isn't exposing presence information to you.
*/
type GetPresenceNotFound struct {
}

func (o *GetPresenceNotFound) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/presence/{userId}/status][%d] getPresenceNotFound ", 404)
}

func (o *GetPresenceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
