// Code generated by go-swagger; DO NOT EDIT.

package room_directory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// NewSetRoomAliasParams creates a new SetRoomAliasParams object
// with the default values initialized.
func NewSetRoomAliasParams() *SetRoomAliasParams {
	var ()
	return &SetRoomAliasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetRoomAliasParamsWithTimeout creates a new SetRoomAliasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetRoomAliasParamsWithTimeout(timeout time.Duration) *SetRoomAliasParams {
	var ()
	return &SetRoomAliasParams{

		timeout: timeout,
	}
}

// NewSetRoomAliasParamsWithContext creates a new SetRoomAliasParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetRoomAliasParamsWithContext(ctx context.Context) *SetRoomAliasParams {
	var ()
	return &SetRoomAliasParams{

		Context: ctx,
	}
}

// NewSetRoomAliasParamsWithHTTPClient creates a new SetRoomAliasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetRoomAliasParamsWithHTTPClient(client *http.Client) *SetRoomAliasParams {
	var ()
	return &SetRoomAliasParams{
		HTTPClient: client,
	}
}

/*SetRoomAliasParams contains all the parameters to send to the API endpoint
for the set room alias operation typically these are written to a http.Request
*/
type SetRoomAliasParams struct {

	/*RoomAlias
	  The room alias to set.

	*/
	RoomAlias string
	/*RoomInfo
	  Information about this room alias.

	*/
	RoomInfo *models.SetRoomAliasParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set room alias params
func (o *SetRoomAliasParams) WithTimeout(timeout time.Duration) *SetRoomAliasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set room alias params
func (o *SetRoomAliasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set room alias params
func (o *SetRoomAliasParams) WithContext(ctx context.Context) *SetRoomAliasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set room alias params
func (o *SetRoomAliasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set room alias params
func (o *SetRoomAliasParams) WithHTTPClient(client *http.Client) *SetRoomAliasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set room alias params
func (o *SetRoomAliasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoomAlias adds the roomAlias to the set room alias params
func (o *SetRoomAliasParams) WithRoomAlias(roomAlias string) *SetRoomAliasParams {
	o.SetRoomAlias(roomAlias)
	return o
}

// SetRoomAlias adds the roomAlias to the set room alias params
func (o *SetRoomAliasParams) SetRoomAlias(roomAlias string) {
	o.RoomAlias = roomAlias
}

// WithRoomInfo adds the roomInfo to the set room alias params
func (o *SetRoomAliasParams) WithRoomInfo(roomInfo *models.SetRoomAliasParamsBody) *SetRoomAliasParams {
	o.SetRoomInfo(roomInfo)
	return o
}

// SetRoomInfo adds the roomInfo to the set room alias params
func (o *SetRoomAliasParams) SetRoomInfo(roomInfo *models.SetRoomAliasParamsBody) {
	o.RoomInfo = roomInfo
}

// WriteToRequest writes these params to a swagger request
func (o *SetRoomAliasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param roomAlias
	if err := r.SetPathParam("roomAlias", o.RoomAlias); err != nil {
		return err
	}

	if o.RoomInfo != nil {
		if err := r.SetBodyParam(o.RoomInfo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
