// Code generated by go-swagger; DO NOT EDIT.

package room_membership

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// NewKickParams creates a new KickParams object
// with the default values initialized.
func NewKickParams() *KickParams {
	var ()
	return &KickParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKickParamsWithTimeout creates a new KickParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKickParamsWithTimeout(timeout time.Duration) *KickParams {
	var ()
	return &KickParams{

		timeout: timeout,
	}
}

// NewKickParamsWithContext creates a new KickParams object
// with the default values initialized, and the ability to set a context for a request
func NewKickParamsWithContext(ctx context.Context) *KickParams {
	var ()
	return &KickParams{

		Context: ctx,
	}
}

// NewKickParamsWithHTTPClient creates a new KickParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKickParamsWithHTTPClient(client *http.Client) *KickParams {
	var ()
	return &KickParams{
		HTTPClient: client,
	}
}

/*KickParams contains all the parameters to send to the API endpoint
for the kick operation typically these are written to a http.Request
*/
type KickParams struct {

	/*Body*/
	Body *models.KickParamsBody
	/*RoomID
	  The room identifier (not alias) from which the user should be kicked.

	*/
	RoomID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the kick params
func (o *KickParams) WithTimeout(timeout time.Duration) *KickParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kick params
func (o *KickParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kick params
func (o *KickParams) WithContext(ctx context.Context) *KickParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kick params
func (o *KickParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kick params
func (o *KickParams) WithHTTPClient(client *http.Client) *KickParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kick params
func (o *KickParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the kick params
func (o *KickParams) WithBody(body *models.KickParamsBody) *KickParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kick params
func (o *KickParams) SetBody(body *models.KickParamsBody) {
	o.Body = body
}

// WithRoomID adds the roomID to the kick params
func (o *KickParams) WithRoomID(roomID string) *KickParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the kick params
func (o *KickParams) SetRoomID(roomID string) {
	o.RoomID = roomID
}

// WriteToRequest writes these params to a swagger request
func (o *KickParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param roomId
	if err := r.SetPathParam("roomId", o.RoomID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
