// Code generated by go-swagger; DO NOT EDIT.

package end_to_end_encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// QueryKeysReader is a Reader for the QueryKeys structure.
type QueryKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQueryKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryKeysOK creates a QueryKeysOK with default headers values
func NewQueryKeysOK() *QueryKeysOK {
	return &QueryKeysOK{}
}

/*QueryKeysOK handles this case with default header values.

The device information
*/
type QueryKeysOK struct {
	Payload *models.QueryKeysOKBody
}

func (o *QueryKeysOK) Error() string {
	return fmt.Sprintf("[POST /_matrix/client/r0/keys/query][%d] queryKeysOK  %+v", 200, o.Payload)
}

func (o *QueryKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QueryKeysOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
