// Code generated by go-swagger; DO NOT EDIT.

package room_membership

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// NewUnbanParams creates a new UnbanParams object
// with the default values initialized.
func NewUnbanParams() *UnbanParams {
	var ()
	return &UnbanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnbanParamsWithTimeout creates a new UnbanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnbanParamsWithTimeout(timeout time.Duration) *UnbanParams {
	var ()
	return &UnbanParams{

		timeout: timeout,
	}
}

// NewUnbanParamsWithContext creates a new UnbanParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnbanParamsWithContext(ctx context.Context) *UnbanParams {
	var ()
	return &UnbanParams{

		Context: ctx,
	}
}

// NewUnbanParamsWithHTTPClient creates a new UnbanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnbanParamsWithHTTPClient(client *http.Client) *UnbanParams {
	var ()
	return &UnbanParams{
		HTTPClient: client,
	}
}

/*UnbanParams contains all the parameters to send to the API endpoint
for the unban operation typically these are written to a http.Request
*/
type UnbanParams struct {

	/*Body*/
	Body *models.UnbanParamsBody
	/*RoomID
	  The room identifier (not alias) from which the user should be unbanned.

	*/
	RoomID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unban params
func (o *UnbanParams) WithTimeout(timeout time.Duration) *UnbanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unban params
func (o *UnbanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unban params
func (o *UnbanParams) WithContext(ctx context.Context) *UnbanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unban params
func (o *UnbanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unban params
func (o *UnbanParams) WithHTTPClient(client *http.Client) *UnbanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unban params
func (o *UnbanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the unban params
func (o *UnbanParams) WithBody(body *models.UnbanParamsBody) *UnbanParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the unban params
func (o *UnbanParams) SetBody(body *models.UnbanParamsBody) {
	o.Body = body
}

// WithRoomID adds the roomID to the unban params
func (o *UnbanParams) WithRoomID(roomID string) *UnbanParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the unban params
func (o *UnbanParams) SetRoomID(roomID string) {
	o.RoomID = roomID
}

// WriteToRequest writes these params to a swagger request
func (o *UnbanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param roomId
	if err := r.SetPathParam("roomId", o.RoomID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
