// Code generated by go-swagger; DO NOT EDIT.

package session_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLogoutAllParams creates a new LogoutAllParams object
// with the default values initialized.
func NewLogoutAllParams() *LogoutAllParams {

	return &LogoutAllParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLogoutAllParamsWithTimeout creates a new LogoutAllParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLogoutAllParamsWithTimeout(timeout time.Duration) *LogoutAllParams {

	return &LogoutAllParams{

		timeout: timeout,
	}
}

// NewLogoutAllParamsWithContext creates a new LogoutAllParams object
// with the default values initialized, and the ability to set a context for a request
func NewLogoutAllParamsWithContext(ctx context.Context) *LogoutAllParams {

	return &LogoutAllParams{

		Context: ctx,
	}
}

// NewLogoutAllParamsWithHTTPClient creates a new LogoutAllParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLogoutAllParamsWithHTTPClient(client *http.Client) *LogoutAllParams {

	return &LogoutAllParams{
		HTTPClient: client,
	}
}

/*LogoutAllParams contains all the parameters to send to the API endpoint
for the logout all operation typically these are written to a http.Request
*/
type LogoutAllParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the logout all params
func (o *LogoutAllParams) WithTimeout(timeout time.Duration) *LogoutAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the logout all params
func (o *LogoutAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the logout all params
func (o *LogoutAllParams) WithContext(ctx context.Context) *LogoutAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the logout all params
func (o *LogoutAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the logout all params
func (o *LogoutAllParams) WithHTTPClient(client *http.Client) *LogoutAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the logout all params
func (o *LogoutAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LogoutAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
