// Code generated by go-swagger; DO NOT EDIT.

package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePushRuleReader is a Reader for the DeletePushRule structure.
type DeletePushRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePushRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePushRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePushRuleOK creates a DeletePushRuleOK with default headers values
func NewDeletePushRuleOK() *DeletePushRuleOK {
	return &DeletePushRuleOK{}
}

/*DeletePushRuleOK handles this case with default header values.

The push rule was deleted.
*/
type DeletePushRuleOK struct {
	Payload DeletePushRuleOKBody
}

func (o *DeletePushRuleOK) Error() string {
	return fmt.Sprintf("[DELETE /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}][%d] deletePushRuleOK  %+v", 200, o.Payload)
}

func (o *DeletePushRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeletePushRuleOKBody delete push rule o k body
swagger:model DeletePushRuleOKBody
*/
type DeletePushRuleOKBody interface{}
