// Code generated by go-swagger; DO NOT EDIT.

package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// NewSetPushRuleActionsParams creates a new SetPushRuleActionsParams object
// with the default values initialized.
func NewSetPushRuleActionsParams() *SetPushRuleActionsParams {
	var ()
	return &SetPushRuleActionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetPushRuleActionsParamsWithTimeout creates a new SetPushRuleActionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetPushRuleActionsParamsWithTimeout(timeout time.Duration) *SetPushRuleActionsParams {
	var ()
	return &SetPushRuleActionsParams{

		timeout: timeout,
	}
}

// NewSetPushRuleActionsParamsWithContext creates a new SetPushRuleActionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetPushRuleActionsParamsWithContext(ctx context.Context) *SetPushRuleActionsParams {
	var ()
	return &SetPushRuleActionsParams{

		Context: ctx,
	}
}

// NewSetPushRuleActionsParamsWithHTTPClient creates a new SetPushRuleActionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetPushRuleActionsParamsWithHTTPClient(client *http.Client) *SetPushRuleActionsParams {
	var ()
	return &SetPushRuleActionsParams{
		HTTPClient: client,
	}
}

/*SetPushRuleActionsParams contains all the parameters to send to the API endpoint
for the set push rule actions operation typically these are written to a http.Request
*/
type SetPushRuleActionsParams struct {

	/*Body
	  The action(s) to perform when the conditions for this rule are met.


	*/
	Body *models.SetPushRuleActionsParamsBody
	/*Kind
	  The kind of rule


	*/
	Kind string
	/*RuleID
	  The identifier for the rule.


	*/
	RuleID string
	/*Scope
	  ``global`` to specify global rules.

	*/
	Scope string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set push rule actions params
func (o *SetPushRuleActionsParams) WithTimeout(timeout time.Duration) *SetPushRuleActionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set push rule actions params
func (o *SetPushRuleActionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set push rule actions params
func (o *SetPushRuleActionsParams) WithContext(ctx context.Context) *SetPushRuleActionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set push rule actions params
func (o *SetPushRuleActionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set push rule actions params
func (o *SetPushRuleActionsParams) WithHTTPClient(client *http.Client) *SetPushRuleActionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set push rule actions params
func (o *SetPushRuleActionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set push rule actions params
func (o *SetPushRuleActionsParams) WithBody(body *models.SetPushRuleActionsParamsBody) *SetPushRuleActionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set push rule actions params
func (o *SetPushRuleActionsParams) SetBody(body *models.SetPushRuleActionsParamsBody) {
	o.Body = body
}

// WithKind adds the kind to the set push rule actions params
func (o *SetPushRuleActionsParams) WithKind(kind string) *SetPushRuleActionsParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the set push rule actions params
func (o *SetPushRuleActionsParams) SetKind(kind string) {
	o.Kind = kind
}

// WithRuleID adds the ruleID to the set push rule actions params
func (o *SetPushRuleActionsParams) WithRuleID(ruleID string) *SetPushRuleActionsParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the set push rule actions params
func (o *SetPushRuleActionsParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WithScope adds the scope to the set push rule actions params
func (o *SetPushRuleActionsParams) WithScope(scope string) *SetPushRuleActionsParams {
	o.SetScope(scope)
	return o
}

// SetScope adds the scope to the set push rule actions params
func (o *SetPushRuleActionsParams) SetScope(scope string) {
	o.Scope = scope
}

// WriteToRequest writes these params to a swagger request
func (o *SetPushRuleActionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param kind
	if err := r.SetPathParam("kind", o.Kind); err != nil {
		return err
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID); err != nil {
		return err
	}

	// path param scope
	if err := r.SetPathParam("scope", o.Scope); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
