// Code generated by go-swagger; DO NOT EDIT.

package room_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPublicRoomsParams creates a new GetPublicRoomsParams object
// with the default values initialized.
func NewGetPublicRoomsParams() *GetPublicRoomsParams {
	var ()
	return &GetPublicRoomsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicRoomsParamsWithTimeout creates a new GetPublicRoomsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPublicRoomsParamsWithTimeout(timeout time.Duration) *GetPublicRoomsParams {
	var ()
	return &GetPublicRoomsParams{

		timeout: timeout,
	}
}

// NewGetPublicRoomsParamsWithContext creates a new GetPublicRoomsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPublicRoomsParamsWithContext(ctx context.Context) *GetPublicRoomsParams {
	var ()
	return &GetPublicRoomsParams{

		Context: ctx,
	}
}

// NewGetPublicRoomsParamsWithHTTPClient creates a new GetPublicRoomsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPublicRoomsParamsWithHTTPClient(client *http.Client) *GetPublicRoomsParams {
	var ()
	return &GetPublicRoomsParams{
		HTTPClient: client,
	}
}

/*GetPublicRoomsParams contains all the parameters to send to the API endpoint
for the get public rooms operation typically these are written to a http.Request
*/
type GetPublicRoomsParams struct {

	/*Limit
	  Limit the number of results returned.

	*/
	Limit *float64
	/*Server
	  The server to fetch the public room lists from. Defaults to the
	local server.

	*/
	Server *string
	/*Since
	  A pagination token from a previous request, allowing clients to
	get the next (or previous) batch of rooms.
	The direction of pagination is specified solely by which token
	is supplied, rather than via an explicit flag.

	*/
	Since *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get public rooms params
func (o *GetPublicRoomsParams) WithTimeout(timeout time.Duration) *GetPublicRoomsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get public rooms params
func (o *GetPublicRoomsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get public rooms params
func (o *GetPublicRoomsParams) WithContext(ctx context.Context) *GetPublicRoomsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get public rooms params
func (o *GetPublicRoomsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get public rooms params
func (o *GetPublicRoomsParams) WithHTTPClient(client *http.Client) *GetPublicRoomsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get public rooms params
func (o *GetPublicRoomsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get public rooms params
func (o *GetPublicRoomsParams) WithLimit(limit *float64) *GetPublicRoomsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get public rooms params
func (o *GetPublicRoomsParams) SetLimit(limit *float64) {
	o.Limit = limit
}

// WithServer adds the server to the get public rooms params
func (o *GetPublicRoomsParams) WithServer(server *string) *GetPublicRoomsParams {
	o.SetServer(server)
	return o
}

// SetServer adds the server to the get public rooms params
func (o *GetPublicRoomsParams) SetServer(server *string) {
	o.Server = server
}

// WithSince adds the since to the get public rooms params
func (o *GetPublicRoomsParams) WithSince(since *string) *GetPublicRoomsParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get public rooms params
func (o *GetPublicRoomsParams) SetSince(since *string) {
	o.Since = since
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicRoomsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit float64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatFloat64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Server != nil {

		// query param server
		var qrServer string
		if o.Server != nil {
			qrServer = *o.Server
		}
		qServer := qrServer
		if qServer != "" {
			if err := r.SetQueryParam("server", qServer); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince string
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := qrSince
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
