// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BanParamsBody ban params body
// swagger:model banParamsBody
type BanParamsBody struct {

	// The reason the user has been banned. This will be supplied as the ``reason`` on the target's updated `m.room.member`_ event.
	Reason string `json:"reason,omitempty"`

	// The fully qualified user ID of the user being banned.
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this ban params body
func (m *BanParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BanParamsBody) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BanParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BanParamsBody) UnmarshalBinary(b []byte) error {
	var res BanParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
