// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateRoomParamsBodyInitialStateItems StateEvent
// swagger:model createRoomParamsBodyInitialStateItems
type CreateRoomParamsBodyInitialStateItems struct {

	// The content of the event.
	// Required: true
	Content interface{} `json:"content"`

	// The state_key of the state event. Defaults to an empty string.
	StateKey string `json:"state_key,omitempty"`

	// The type of event to send.
	// Required: true
	Type *string `json:"type"`
}

// Validate validates this create room params body initial state items
func (m *CreateRoomParamsBodyInitialStateItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateRoomParamsBodyInitialStateItems) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("content", "body", m.Content); err != nil {
		return err
	}

	return nil
}

func (m *CreateRoomParamsBodyInitialStateItems) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateRoomParamsBodyInitialStateItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateRoomParamsBodyInitialStateItems) UnmarshalBinary(b []byte) error {
	var res CreateRoomParamsBodyInitialStateItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
