// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Delete3pidFromAccountParamsBody delete3pid from account params body
// swagger:model delete3pidFromAccountParamsBody
type Delete3pidFromAccountParamsBody struct {

	// The third party address being removed.
	// Required: true
	Address *string `json:"address"`

	// The medium of the third party identifier being removed.
	// Required: true
	// Enum: [email msisdn]
	Medium *string `json:"medium"`
}

// Validate validates this delete3pid from account params body
func (m *Delete3pidFromAccountParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedium(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Delete3pidFromAccountParamsBody) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

var delete3pidFromAccountParamsBodyTypeMediumPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["email","msisdn"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		delete3pidFromAccountParamsBodyTypeMediumPropEnum = append(delete3pidFromAccountParamsBodyTypeMediumPropEnum, v)
	}
}

const (

	// Delete3pidFromAccountParamsBodyMediumEmail captures enum value "email"
	Delete3pidFromAccountParamsBodyMediumEmail string = "email"

	// Delete3pidFromAccountParamsBodyMediumMsisdn captures enum value "msisdn"
	Delete3pidFromAccountParamsBodyMediumMsisdn string = "msisdn"
)

// prop value enum
func (m *Delete3pidFromAccountParamsBody) validateMediumEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, delete3pidFromAccountParamsBodyTypeMediumPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Delete3pidFromAccountParamsBody) validateMedium(formats strfmt.Registry) error {

	if err := validate.Required("medium", "body", m.Medium); err != nil {
		return err
	}

	// value enum
	if err := m.validateMediumEnum("medium", "body", *m.Medium); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Delete3pidFromAccountParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Delete3pidFromAccountParamsBody) UnmarshalBinary(b []byte) error {
	var res Delete3pidFromAccountParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
