// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetJoinedMembersByRoomOKBody get joined members by room o k body
// swagger:model getJoinedMembersByRoomOKBody
type GetJoinedMembersByRoomOKBody struct {

	// joined
	Joined GetJoinedMembersByRoomOKBodyJoined `json:"joined,omitempty"`
}

// Validate validates this get joined members by room o k body
func (m *GetJoinedMembersByRoomOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJoined(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetJoinedMembersByRoomOKBody) validateJoined(formats strfmt.Registry) error {

	if swag.IsZero(m.Joined) { // not required
		return nil
	}

	if err := m.Joined.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("joined")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetJoinedMembersByRoomOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetJoinedMembersByRoomOKBody) UnmarshalBinary(b []byte) error {
	var res GetJoinedMembersByRoomOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
