// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetDisplayNameOKBody get display name o k body
// swagger:model getDisplayNameOKBody
type GetDisplayNameOKBody struct {

	// The user's display name if they have set one, otherwise not present.
	Displayname string `json:"displayname,omitempty"`
}

// Validate validates this get display name o k body
func (m *GetDisplayNameOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetDisplayNameOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetDisplayNameOKBody) UnmarshalBinary(b []byte) error {
	var res GetDisplayNameOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
