// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetRoomIDByAliasOKBody get room Id by alias o k body
// swagger:model getRoomIdByAliasOKBody
type GetRoomIDByAliasOKBody struct {

	// The room ID for this room alias.
	RoomID string `json:"room_id,omitempty"`

	// A list of servers that are aware of this room alias.
	Servers []string `json:"servers"`
}

// Validate validates this get room Id by alias o k body
func (m *GetRoomIDByAliasOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetRoomIDByAliasOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetRoomIDByAliasOKBody) UnmarshalBinary(b []byte) error {
	var res GetRoomIDByAliasOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
