// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetURLPreviewOKBody get Url preview o k body
// swagger:model getUrlPreviewOKBody
type GetURLPreviewOKBody struct {

	// The byte-size of the image. Omitted if there is no image attached.
	MatrixImageSize int64 `json:"matrix:image:size,omitempty"`

	// An MXC URI to the image. Omitted if there is no image.
	OgImage string `json:"og:image,omitempty"`
}

// Validate validates this get Url preview o k body
func (m *GetURLPreviewOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetURLPreviewOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetURLPreviewOKBody) UnmarshalBinary(b []byte) error {
	var res GetURLPreviewOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
