// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InitialSyncOKBodyRoomsItemsStateItems StateEvent
// swagger:model initialSyncOKBodyRoomsItemsStateItems
type InitialSyncOKBodyRoomsItemsStateItems struct {
	InitialSyncOKBodyRoomsItemsStateItemsAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *InitialSyncOKBodyRoomsItemsStateItems) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 InitialSyncOKBodyRoomsItemsStateItemsAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.InitialSyncOKBodyRoomsItemsStateItemsAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m InitialSyncOKBodyRoomsItemsStateItems) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.InitialSyncOKBodyRoomsItemsStateItemsAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this initial sync o k body rooms items state items
func (m *InitialSyncOKBodyRoomsItemsStateItems) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with InitialSyncOKBodyRoomsItemsStateItemsAllOf0
	if err := m.InitialSyncOKBodyRoomsItemsStateItemsAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InitialSyncOKBodyRoomsItemsStateItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InitialSyncOKBodyRoomsItemsStateItems) UnmarshalBinary(b []byte) error {
	var res InitialSyncOKBodyRoomsItemsStateItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
