// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0 Room Event
//
// In addition to the Event fields, Room Events have the following additional fields.
// swagger:model searchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0
type SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0 struct {
	SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0AllOf0

	// The ID of the room associated with this event. Will not be present on events
	// that arrive through ``/sync``, despite being required everywhere else.
	// Required: true
	RoomID *string `json:"room_id"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0AllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0AllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0AllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this search o k body search categories room events state additional properties items all of0
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0AllOf0
	if err := m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0AllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoomID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0) validateRoomID(formats strfmt.Registry) error {

	if err := validate.Required("room_id", "body", m.RoomID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0) UnmarshalBinary(b []byte) error {
	var res SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
