// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems State Event
//
// In addition to the Room Event fields, State Events have the following additional fields.
// swagger:model searchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems
type SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems struct {
	SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0

	SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0 = aO0

	// AO1
	var aO1 SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this search o k body search categories room events state additional properties items
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0
	if err := m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf1
	if err := m.SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItemsAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems) UnmarshalBinary(b []byte) error {
	var res SearchOKBodySearchCategoriesRoomEventsStateAdditionalPropertiesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
