// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SetDisplayNameParamsBody set display name params body
// swagger:model setDisplayNameParamsBody
type SetDisplayNameParamsBody struct {

	// The new display name for this user.
	Displayname string `json:"displayname,omitempty"`
}

// Validate validates this set display name params body
func (m *SetDisplayNameParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetDisplayNameParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetDisplayNameParamsBody) UnmarshalBinary(b []byte) error {
	var res SetDisplayNameParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
