// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// SyncOKBodyRoomsLeave Left rooms
//
// The rooms that the user has left or been banned from.
// swagger:model syncOKBodyRoomsLeave
type SyncOKBodyRoomsLeave map[string]SyncOKBodyRoomsLeaveAdditionalProperties

// Validate validates this sync o k body rooms leave
func (m SyncOKBodyRoomsLeave) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", SyncOKBodyRoomsLeave(m)); err != nil {
		return err
	}

	for k := range m {

		if val, ok := m[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
