// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData Account Data
//
// The private data that this user has attached to
// this room.
// swagger:model syncOKBodyRoomsLeaveAdditionalPropertiesAccountData
type SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData struct {
	SyncOKBodyRoomsLeaveAdditionalPropertiesAccountDataAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SyncOKBodyRoomsLeaveAdditionalPropertiesAccountDataAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SyncOKBodyRoomsLeaveAdditionalPropertiesAccountDataAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.SyncOKBodyRoomsLeaveAdditionalPropertiesAccountDataAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this sync o k body rooms leave additional properties account data
func (m *SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SyncOKBodyRoomsLeaveAdditionalPropertiesAccountDataAllOf0
	if err := m.SyncOKBodyRoomsLeaveAdditionalPropertiesAccountDataAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData) UnmarshalBinary(b []byte) error {
	var res SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
