// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// SyncOKBodyRoomsInvite Invited Rooms
//
// The rooms that the user has been invited to.
// swagger:model syncOKBodyRoomsInvite
type SyncOKBodyRoomsInvite map[string]SyncOKBodyRoomsInviteAdditionalProperties

// Validate validates this sync o k body rooms invite
func (m SyncOKBodyRoomsInvite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", SyncOKBodyRoomsInvite(m)); err != nil {
		return err
	}

	for k := range m {

		if val, ok := m[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
