// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SyncOKBodyRoomsLeaveAdditionalProperties Left Room
// swagger:model syncOKBodyRoomsLeaveAdditionalProperties
type SyncOKBodyRoomsLeaveAdditionalProperties struct {

	// account data
	AccountData *SyncOKBodyRoomsLeaveAdditionalPropertiesAccountData `json:"account_data,omitempty"`

	// state
	State *SyncOKBodyRoomsLeaveAdditionalPropertiesState `json:"state,omitempty"`

	// timeline
	Timeline *SyncOKBodyRoomsLeaveAdditionalPropertiesTimeline `json:"timeline,omitempty"`
}

// Validate validates this sync o k body rooms leave additional properties
func (m *SyncOKBodyRoomsLeaveAdditionalProperties) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeline(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SyncOKBodyRoomsLeaveAdditionalProperties) validateAccountData(formats strfmt.Registry) error {

	if swag.IsZero(m.AccountData) { // not required
		return nil
	}

	if m.AccountData != nil {
		if err := m.AccountData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("account_data")
			}
			return err
		}
	}

	return nil
}

func (m *SyncOKBodyRoomsLeaveAdditionalProperties) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if m.State != nil {
		if err := m.State.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("state")
			}
			return err
		}
	}

	return nil
}

func (m *SyncOKBodyRoomsLeaveAdditionalProperties) validateTimeline(formats strfmt.Registry) error {

	if swag.IsZero(m.Timeline) { // not required
		return nil
	}

	if m.Timeline != nil {
		if err := m.Timeline.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("timeline")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SyncOKBodyRoomsLeaveAdditionalProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyncOKBodyRoomsLeaveAdditionalProperties) UnmarshalBinary(b []byte) error {
	var res SyncOKBodyRoomsLeaveAdditionalProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
