// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UploadKeysParamsBody upload keys params body
// swagger:model uploadKeysParamsBody
type UploadKeysParamsBody struct {

	// device keys
	DeviceKeys *UploadKeysParamsBodyDeviceKeys `json:"device_keys,omitempty"`

	// One-time public keys for "pre-key" messages.  The names of
	// the properties should be in the format
	// ``<algorithm>:<key_id>``. The format of the key is determined
	// by the key algorithm.
	//
	// May be absent if no new one-time keys are required.
	OneTimeKeys map[string]string `json:"one_time_keys,omitempty"`
}

// Validate validates this upload keys params body
func (m *UploadKeysParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UploadKeysParamsBody) validateDeviceKeys(formats strfmt.Registry) error {

	if swag.IsZero(m.DeviceKeys) { // not required
		return nil
	}

	if m.DeviceKeys != nil {
		if err := m.DeviceKeys.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("device_keys")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UploadKeysParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadKeysParamsBody) UnmarshalBinary(b []byte) error {
	var res UploadKeysParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
