// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDisplayNameParams creates a new GetDisplayNameParams object
// with the default values initialized.
func NewGetDisplayNameParams() *GetDisplayNameParams {
	var ()
	return &GetDisplayNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDisplayNameParamsWithTimeout creates a new GetDisplayNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDisplayNameParamsWithTimeout(timeout time.Duration) *GetDisplayNameParams {
	var ()
	return &GetDisplayNameParams{

		timeout: timeout,
	}
}

// NewGetDisplayNameParamsWithContext creates a new GetDisplayNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDisplayNameParamsWithContext(ctx context.Context) *GetDisplayNameParams {
	var ()
	return &GetDisplayNameParams{

		Context: ctx,
	}
}

// NewGetDisplayNameParamsWithHTTPClient creates a new GetDisplayNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDisplayNameParamsWithHTTPClient(client *http.Client) *GetDisplayNameParams {
	var ()
	return &GetDisplayNameParams{
		HTTPClient: client,
	}
}

/*GetDisplayNameParams contains all the parameters to send to the API endpoint
for the get display name operation typically these are written to a http.Request
*/
type GetDisplayNameParams struct {

	/*UserID
	  The user whose display name to get.

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get display name params
func (o *GetDisplayNameParams) WithTimeout(timeout time.Duration) *GetDisplayNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get display name params
func (o *GetDisplayNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get display name params
func (o *GetDisplayNameParams) WithContext(ctx context.Context) *GetDisplayNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get display name params
func (o *GetDisplayNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get display name params
func (o *GetDisplayNameParams) WithHTTPClient(client *http.Client) *GetDisplayNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get display name params
func (o *GetDisplayNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get display name params
func (o *GetDisplayNameParams) WithUserID(userID string) *GetDisplayNameParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get display name params
func (o *GetDisplayNameParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDisplayNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
