// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetAccount3PIdsReader is a Reader for the GetAccount3PIds structure.
type GetAccount3PIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccount3PIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAccount3PIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccount3PIdsOK creates a GetAccount3PIdsOK with default headers values
func NewGetAccount3PIdsOK() *GetAccount3PIdsOK {
	return &GetAccount3PIdsOK{}
}

/*GetAccount3PIdsOK handles this case with default header values.

The lookup was successful.
*/
type GetAccount3PIdsOK struct {
	Payload *models.GetAccount3PIdsOKBody
}

func (o *GetAccount3PIdsOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/account/3pid][%d] getAccount3PIdsOK  %+v", 200, o.Payload)
}

func (o *GetAccount3PIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetAccount3PIdsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
