// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetTokenOwnerReader is a Reader for the GetTokenOwner structure.
type GetTokenOwnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokenOwnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTokenOwnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetTokenOwnerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetTokenOwnerForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewGetTokenOwnerTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTokenOwnerOK creates a GetTokenOwnerOK with default headers values
func NewGetTokenOwnerOK() *GetTokenOwnerOK {
	return &GetTokenOwnerOK{}
}

/*GetTokenOwnerOK handles this case with default header values.

The token belongs to a known user.
*/
type GetTokenOwnerOK struct {
	Payload *models.GetTokenOwnerOKBody
}

func (o *GetTokenOwnerOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/account/whoami][%d] getTokenOwnerOK  %+v", 200, o.Payload)
}

func (o *GetTokenOwnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTokenOwnerOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokenOwnerUnauthorized creates a GetTokenOwnerUnauthorized with default headers values
func NewGetTokenOwnerUnauthorized() *GetTokenOwnerUnauthorized {
	return &GetTokenOwnerUnauthorized{}
}

/*GetTokenOwnerUnauthorized handles this case with default header values.

The token is not recognised
*/
type GetTokenOwnerUnauthorized struct {
	Payload *models.GetTokenOwnerUnauthorizedBody
}

func (o *GetTokenOwnerUnauthorized) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/account/whoami][%d] getTokenOwnerUnauthorized  %+v", 401, o.Payload)
}

func (o *GetTokenOwnerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTokenOwnerUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokenOwnerForbidden creates a GetTokenOwnerForbidden with default headers values
func NewGetTokenOwnerForbidden() *GetTokenOwnerForbidden {
	return &GetTokenOwnerForbidden{}
}

/*GetTokenOwnerForbidden handles this case with default header values.

The appservice cannot masquerade as the user or has not registered them.
*/
type GetTokenOwnerForbidden struct {
	Payload *models.GetTokenOwnerForbiddenBody
}

func (o *GetTokenOwnerForbidden) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/account/whoami][%d] getTokenOwnerForbidden  %+v", 403, o.Payload)
}

func (o *GetTokenOwnerForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTokenOwnerForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokenOwnerTooManyRequests creates a GetTokenOwnerTooManyRequests with default headers values
func NewGetTokenOwnerTooManyRequests() *GetTokenOwnerTooManyRequests {
	return &GetTokenOwnerTooManyRequests{}
}

/*GetTokenOwnerTooManyRequests handles this case with default header values.

This request was rate-limited.
*/
type GetTokenOwnerTooManyRequests struct {
	Payload *models.GetTokenOwnerTooManyRequestsBody
}

func (o *GetTokenOwnerTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/account/whoami][%d] getTokenOwnerTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetTokenOwnerTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTokenOwnerTooManyRequestsBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
