// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetAccountDataParams creates a new SetAccountDataParams object
// with the default values initialized.
func NewSetAccountDataParams() *SetAccountDataParams {
	var ()
	return &SetAccountDataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetAccountDataParamsWithTimeout creates a new SetAccountDataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetAccountDataParamsWithTimeout(timeout time.Duration) *SetAccountDataParams {
	var ()
	return &SetAccountDataParams{

		timeout: timeout,
	}
}

// NewSetAccountDataParamsWithContext creates a new SetAccountDataParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetAccountDataParamsWithContext(ctx context.Context) *SetAccountDataParams {
	var ()
	return &SetAccountDataParams{

		Context: ctx,
	}
}

// NewSetAccountDataParamsWithHTTPClient creates a new SetAccountDataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetAccountDataParamsWithHTTPClient(client *http.Client) *SetAccountDataParams {
	var ()
	return &SetAccountDataParams{
		HTTPClient: client,
	}
}

/*SetAccountDataParams contains all the parameters to send to the API endpoint
for the set account data operation typically these are written to a http.Request
*/
type SetAccountDataParams struct {

	/*Content
	  The content of the account_data

	*/
	Content interface{}
	/*Type
	  The event type of the account_data to set. Custom types should be
	namespaced to avoid clashes.

	*/
	Type string
	/*UserID
	  The id of the user to set account_data for. The access token must be
	authorized to make requests for this user id.

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set account data params
func (o *SetAccountDataParams) WithTimeout(timeout time.Duration) *SetAccountDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set account data params
func (o *SetAccountDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set account data params
func (o *SetAccountDataParams) WithContext(ctx context.Context) *SetAccountDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set account data params
func (o *SetAccountDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set account data params
func (o *SetAccountDataParams) WithHTTPClient(client *http.Client) *SetAccountDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set account data params
func (o *SetAccountDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContent adds the content to the set account data params
func (o *SetAccountDataParams) WithContent(content interface{}) *SetAccountDataParams {
	o.SetContent(content)
	return o
}

// SetContent adds the content to the set account data params
func (o *SetAccountDataParams) SetContent(content interface{}) {
	o.Content = content
}

// WithType adds the typeVar to the set account data params
func (o *SetAccountDataParams) WithType(typeVar string) *SetAccountDataParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the set account data params
func (o *SetAccountDataParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WithUserID adds the userID to the set account data params
func (o *SetAccountDataParams) WithUserID(userID string) *SetAccountDataParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the set account data params
func (o *SetAccountDataParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *SetAccountDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Content != nil {
		if err := r.SetBodyParam(o.Content); err != nil {
			return err
		}
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
