// Code generated by go-swagger; DO NOT EDIT.

package v_o_ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTurnServerParams creates a new GetTurnServerParams object
// with the default values initialized.
func NewGetTurnServerParams() *GetTurnServerParams {

	return &GetTurnServerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTurnServerParamsWithTimeout creates a new GetTurnServerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTurnServerParamsWithTimeout(timeout time.Duration) *GetTurnServerParams {

	return &GetTurnServerParams{

		timeout: timeout,
	}
}

// NewGetTurnServerParamsWithContext creates a new GetTurnServerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTurnServerParamsWithContext(ctx context.Context) *GetTurnServerParams {

	return &GetTurnServerParams{

		Context: ctx,
	}
}

// NewGetTurnServerParamsWithHTTPClient creates a new GetTurnServerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTurnServerParamsWithHTTPClient(client *http.Client) *GetTurnServerParams {

	return &GetTurnServerParams{
		HTTPClient: client,
	}
}

/*GetTurnServerParams contains all the parameters to send to the API endpoint
for the get turn server operation typically these are written to a http.Request
*/
type GetTurnServerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get turn server params
func (o *GetTurnServerParams) WithTimeout(timeout time.Duration) *GetTurnServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get turn server params
func (o *GetTurnServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get turn server params
func (o *GetTurnServerParams) WithContext(ctx context.Context) *GetTurnServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get turn server params
func (o *GetTurnServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get turn server params
func (o *GetTurnServerParams) WithHTTPClient(client *http.Client) *GetTurnServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get turn server params
func (o *GetTurnServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTurnServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
