// Code generated by go-swagger; DO NOT EDIT.

package reporting_content

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new reporting content API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for reporting content API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ReportContent reports an event as inappropriate

Reports an event as inappropriate to the server, which may then notify
the appropriate people.
*/
func (a *Client) ReportContent(params *ReportContentParams, authInfo runtime.ClientAuthInfoWriter) (*ReportContentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReportContentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "reportContent",
		Method:             "POST",
		PathPattern:        "/_matrix/client/unstable/rooms/{roomId}/report/{eventId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ReportContentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ReportContentOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
