// Code generated by go-swagger; DO NOT EDIT.

package reporting_content

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// NewReportContentParams creates a new ReportContentParams object
// with the default values initialized.
func NewReportContentParams() *ReportContentParams {
	var ()
	return &ReportContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReportContentParamsWithTimeout creates a new ReportContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReportContentParamsWithTimeout(timeout time.Duration) *ReportContentParams {
	var ()
	return &ReportContentParams{

		timeout: timeout,
	}
}

// NewReportContentParamsWithContext creates a new ReportContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewReportContentParamsWithContext(ctx context.Context) *ReportContentParams {
	var ()
	return &ReportContentParams{

		Context: ctx,
	}
}

// NewReportContentParamsWithHTTPClient creates a new ReportContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReportContentParamsWithHTTPClient(client *http.Client) *ReportContentParams {
	var ()
	return &ReportContentParams{
		HTTPClient: client,
	}
}

/*ReportContentParams contains all the parameters to send to the API endpoint
for the report content operation typically these are written to a http.Request
*/
type ReportContentParams struct {

	/*Body*/
	Body *models.ReportContentParamsBody
	/*EventID
	  The event to report.

	*/
	EventID string
	/*RoomID
	  The room in which the event being reported is located.

	*/
	RoomID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the report content params
func (o *ReportContentParams) WithTimeout(timeout time.Duration) *ReportContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the report content params
func (o *ReportContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the report content params
func (o *ReportContentParams) WithContext(ctx context.Context) *ReportContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the report content params
func (o *ReportContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the report content params
func (o *ReportContentParams) WithHTTPClient(client *http.Client) *ReportContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the report content params
func (o *ReportContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the report content params
func (o *ReportContentParams) WithBody(body *models.ReportContentParamsBody) *ReportContentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the report content params
func (o *ReportContentParams) SetBody(body *models.ReportContentParamsBody) {
	o.Body = body
}

// WithEventID adds the eventID to the report content params
func (o *ReportContentParams) WithEventID(eventID string) *ReportContentParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the report content params
func (o *ReportContentParams) SetEventID(eventID string) {
	o.EventID = eventID
}

// WithRoomID adds the roomID to the report content params
func (o *ReportContentParams) WithRoomID(roomID string) *ReportContentParams {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the report content params
func (o *ReportContentParams) SetRoomID(roomID string) {
	o.RoomID = roomID
}

// WriteToRequest writes these params to a swagger request
func (o *ReportContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param eventId
	if err := r.SetPathParam("eventId", o.EventID); err != nil {
		return err
	}

	// path param roomId
	if err := r.SetPathParam("roomId", o.RoomID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
