// Code generated by go-swagger; DO NOT EDIT.

package room_participation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// DefineFilterReader is a Reader for the DefineFilter structure.
type DefineFilterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DefineFilterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDefineFilterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDefineFilterOK creates a DefineFilterOK with default headers values
func NewDefineFilterOK() *DefineFilterOK {
	return &DefineFilterOK{}
}

/*DefineFilterOK handles this case with default header values.

The filter was created.
*/
type DefineFilterOK struct {
	Payload *models.DefineFilterOKBody
}

func (o *DefineFilterOK) Error() string {
	return fmt.Sprintf("[POST /_matrix/client/r0/user/{userId}/filter][%d] defineFilterOK  %+v", 200, o.Payload)
}

func (o *DefineFilterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefineFilterOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
