// Code generated by go-swagger; DO NOT EDIT.

package room_participation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOneEventParams creates a new GetOneEventParams object
// with the default values initialized.
func NewGetOneEventParams() *GetOneEventParams {
	var ()
	return &GetOneEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOneEventParamsWithTimeout creates a new GetOneEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOneEventParamsWithTimeout(timeout time.Duration) *GetOneEventParams {
	var ()
	return &GetOneEventParams{

		timeout: timeout,
	}
}

// NewGetOneEventParamsWithContext creates a new GetOneEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOneEventParamsWithContext(ctx context.Context) *GetOneEventParams {
	var ()
	return &GetOneEventParams{

		Context: ctx,
	}
}

// NewGetOneEventParamsWithHTTPClient creates a new GetOneEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOneEventParamsWithHTTPClient(client *http.Client) *GetOneEventParams {
	var ()
	return &GetOneEventParams{
		HTTPClient: client,
	}
}

/*GetOneEventParams contains all the parameters to send to the API endpoint
for the get one event operation typically these are written to a http.Request
*/
type GetOneEventParams struct {

	/*EventID
	  The event ID to get.

	*/
	EventID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get one event params
func (o *GetOneEventParams) WithTimeout(timeout time.Duration) *GetOneEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get one event params
func (o *GetOneEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get one event params
func (o *GetOneEventParams) WithContext(ctx context.Context) *GetOneEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get one event params
func (o *GetOneEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get one event params
func (o *GetOneEventParams) WithHTTPClient(client *http.Client) *GetOneEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get one event params
func (o *GetOneEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the get one event params
func (o *GetOneEventParams) WithEventID(eventID string) *GetOneEventParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the get one event params
func (o *GetOneEventParams) SetEventID(eventID string) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOneEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param eventId
	if err := r.SetPathParam("eventId", o.EventID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
