// Code generated by go-swagger; DO NOT EDIT.

package room_participation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// GetRoomEventsReader is a Reader for the GetRoomEvents structure.
type GetRoomEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoomEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRoomEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetRoomEventsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRoomEventsOK creates a GetRoomEventsOK with default headers values
func NewGetRoomEventsOK() *GetRoomEventsOK {
	return &GetRoomEventsOK{}
}

/*GetRoomEventsOK handles this case with default header values.

A list of messages with a new token to request more.
*/
type GetRoomEventsOK struct {
	Payload *models.GetRoomEventsOKBody
}

func (o *GetRoomEventsOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/rooms/{roomId}/messages][%d] getRoomEventsOK  %+v", 200, o.Payload)
}

func (o *GetRoomEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetRoomEventsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoomEventsForbidden creates a GetRoomEventsForbidden with default headers values
func NewGetRoomEventsForbidden() *GetRoomEventsForbidden {
	return &GetRoomEventsForbidden{}
}

/*GetRoomEventsForbidden handles this case with default header values.

You aren't a member of the room.

*/
type GetRoomEventsForbidden struct {
}

func (o *GetRoomEventsForbidden) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/rooms/{roomId}/messages][%d] getRoomEventsForbidden ", 403)
}

func (o *GetRoomEventsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
