// Code generated by go-swagger; DO NOT EDIT.

package room_participation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// GetRoomStateReader is a Reader for the GetRoomState structure.
type GetRoomStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoomStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRoomStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetRoomStateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRoomStateOK creates a GetRoomStateOK with default headers values
func NewGetRoomStateOK() *GetRoomStateOK {
	return &GetRoomStateOK{}
}

/*GetRoomStateOK handles this case with default header values.

The current state of the room
*/
type GetRoomStateOK struct {
	Payload []*models.GetRoomStateOKBodyItems
}

func (o *GetRoomStateOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/rooms/{roomId}/state][%d] getRoomStateOK  %+v", 200, o.Payload)
}

func (o *GetRoomStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoomStateForbidden creates a GetRoomStateForbidden with default headers values
func NewGetRoomStateForbidden() *GetRoomStateForbidden {
	return &GetRoomStateForbidden{}
}

/*GetRoomStateForbidden handles this case with default header values.

You aren't a member of the room and weren't previously a member of the room.

*/
type GetRoomStateForbidden struct {
}

func (o *GetRoomStateForbidden) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/rooms/{roomId}/state][%d] getRoomStateForbidden ", 403)
}

func (o *GetRoomStateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
