// Code generated by go-swagger; DO NOT EDIT.

package presence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetPresenceForListReader is a Reader for the GetPresenceForList structure.
type GetPresenceForListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPresenceForListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPresenceForListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPresenceForListOK creates a GetPresenceForListOK with default headers values
func NewGetPresenceForListOK() *GetPresenceForListOK {
	return &GetPresenceForListOK{}
}

/*GetPresenceForListOK handles this case with default header values.

A list of presence events for this list.
*/
type GetPresenceForListOK struct {
	Payload []*models.GetPresenceForListOKBodyItems
}

func (o *GetPresenceForListOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/list/{userId}][%d] getPresenceForListOK  %+v", 200, o.Payload)
}

func (o *GetPresenceForListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
