// Code generated by go-swagger; DO NOT EDIT.

package presence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetPresenceReader is a Reader for the GetPresence structure.
type GetPresenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPresenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPresenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetPresenceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetPresenceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPresenceOK creates a GetPresenceOK with default headers values
func NewGetPresenceOK() *GetPresenceOK {
	return &GetPresenceOK{}
}

/*GetPresenceOK handles this case with default header values.

The presence state for this user.
*/
type GetPresenceOK struct {
	Payload *models.GetPresenceOKBody
}

func (o *GetPresenceOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/{userId}/status][%d] getPresenceOK  %+v", 200, o.Payload)
}

func (o *GetPresenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPresenceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPresenceForbidden creates a GetPresenceForbidden with default headers values
func NewGetPresenceForbidden() *GetPresenceForbidden {
	return &GetPresenceForbidden{}
}

/*GetPresenceForbidden handles this case with default header values.

You are not allowed to see this user's presence status.
*/
type GetPresenceForbidden struct {
	Payload *models.GetPresenceForbiddenBody
}

func (o *GetPresenceForbidden) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/{userId}/status][%d] getPresenceForbidden  %+v", 403, o.Payload)
}

func (o *GetPresenceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPresenceForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPresenceNotFound creates a GetPresenceNotFound with default headers values
func NewGetPresenceNotFound() *GetPresenceNotFound {
	return &GetPresenceNotFound{}
}

/*GetPresenceNotFound handles this case with default header values.

There is no presence state for this user. This user may not exist or
isn't exposing presence information to you.
*/
type GetPresenceNotFound struct {
	Payload *models.GetPresenceNotFoundBody
}

func (o *GetPresenceNotFound) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/{userId}/status][%d] getPresenceNotFound  %+v", 404, o.Payload)
}

func (o *GetPresenceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPresenceNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
