// Code generated by go-swagger; DO NOT EDIT.

package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetPushRuleReader is a Reader for the GetPushRule structure.
type GetPushRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPushRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPushRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPushRuleOK creates a GetPushRuleOK with default headers values
func NewGetPushRuleOK() *GetPushRuleOK {
	return &GetPushRuleOK{}
}

/*GetPushRuleOK handles this case with default header values.

The specific push rule. This will also include keys specific to the
rule itself such as the rule's ``actions`` and ``conditions`` if set.
*/
type GetPushRuleOK struct {
	Payload *models.GetPushRuleOKBody
}

func (o *GetPushRuleOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/pushrules/{scope}/{kind}/{ruleId}][%d] getPushRuleOK  %+v", 200, o.Payload)
}

func (o *GetPushRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPushRuleOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
