// Code generated by go-swagger; DO NOT EDIT.

package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetPushRulesReader is a Reader for the GetPushRules structure.
type GetPushRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPushRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPushRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPushRulesOK creates a GetPushRulesOK with default headers values
func NewGetPushRulesOK() *GetPushRulesOK {
	return &GetPushRulesOK{}
}

/*GetPushRulesOK handles this case with default header values.

All the push rulesets for this user.
*/
type GetPushRulesOK struct {
	Payload *models.GetPushRulesOKBody
}

func (o *GetPushRulesOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/pushrules/][%d] getPushRulesOK  %+v", 200, o.Payload)
}

func (o *GetPushRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPushRulesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
