// Code generated by go-swagger; DO NOT EDIT.

package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SetPushRuleActionsReader is a Reader for the SetPushRuleActions structure.
type SetPushRuleActionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPushRuleActionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetPushRuleActionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPushRuleActionsOK creates a SetPushRuleActionsOK with default headers values
func NewSetPushRuleActionsOK() *SetPushRuleActionsOK {
	return &SetPushRuleActionsOK{}
}

/*SetPushRuleActionsOK handles this case with default header values.

The actions for the push rule were set.
*/
type SetPushRuleActionsOK struct {
	Payload SetPushRuleActionsOKBody
}

func (o *SetPushRuleActionsOK) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/pushrules/{scope}/{kind}/{ruleId}/actions][%d] setPushRuleActionsOK  %+v", 200, o.Payload)
}

func (o *SetPushRuleActionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetPushRuleActionsOKBody set push rule actions o k body
swagger:model SetPushRuleActionsOKBody
*/
type SetPushRuleActionsOKBody interface{}
