// Code generated by go-swagger; DO NOT EDIT.

package push_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SetPushRuleEnabledReader is a Reader for the SetPushRuleEnabled structure.
type SetPushRuleEnabledReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPushRuleEnabledReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetPushRuleEnabledOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPushRuleEnabledOK creates a SetPushRuleEnabledOK with default headers values
func NewSetPushRuleEnabledOK() *SetPushRuleEnabledOK {
	return &SetPushRuleEnabledOK{}
}

/*SetPushRuleEnabledOK handles this case with default header values.

The push rule was enabled or disabled.
*/
type SetPushRuleEnabledOK struct {
	Payload SetPushRuleEnabledOKBody
}

func (o *SetPushRuleEnabledOK) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/pushrules/{scope}/{kind}/{ruleId}/enabled][%d] setPushRuleEnabledOK  %+v", 200, o.Payload)
}

func (o *SetPushRuleEnabledOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetPushRuleEnabledOKBody set push rule enabled o k body
swagger:model SetPushRuleEnabledOKBody
*/
type SetPushRuleEnabledOKBody interface{}
