// Code generated by go-swagger; DO NOT EDIT.

package room_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetPublicRoomsReader is a Reader for the GetPublicRooms structure.
type GetPublicRoomsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPublicRoomsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPublicRoomsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPublicRoomsOK creates a GetPublicRoomsOK with default headers values
func NewGetPublicRoomsOK() *GetPublicRoomsOK {
	return &GetPublicRoomsOK{}
}

/*GetPublicRoomsOK handles this case with default header values.

A list of the rooms on the server.
*/
type GetPublicRoomsOK struct {
	Payload *models.GetPublicRoomsOKBody
}

func (o *GetPublicRoomsOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/publicRooms][%d] getPublicRoomsOK  %+v", 200, o.Payload)
}

func (o *GetPublicRoomsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPublicRoomsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
