// Code generated by go-swagger; DO NOT EDIT.

package application_service_room_directory_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateAppserviceRoomDirectoryVsibilityReader is a Reader for the UpdateAppserviceRoomDirectoryVsibility structure.
type UpdateAppserviceRoomDirectoryVsibilityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAppserviceRoomDirectoryVsibilityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateAppserviceRoomDirectoryVsibilityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateAppserviceRoomDirectoryVsibilityOK creates a UpdateAppserviceRoomDirectoryVsibilityOK with default headers values
func NewUpdateAppserviceRoomDirectoryVsibilityOK() *UpdateAppserviceRoomDirectoryVsibilityOK {
	return &UpdateAppserviceRoomDirectoryVsibilityOK{}
}

/*UpdateAppserviceRoomDirectoryVsibilityOK handles this case with default header values.

The room's directory visibility has been updated.
*/
type UpdateAppserviceRoomDirectoryVsibilityOK struct {
	Payload UpdateAppserviceRoomDirectoryVsibilityOKBody
}

func (o *UpdateAppserviceRoomDirectoryVsibilityOK) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/directory/list/appservice/{networkId}/{roomId}][%d] updateAppserviceRoomDirectoryVsibilityOK  %+v", 200, o.Payload)
}

func (o *UpdateAppserviceRoomDirectoryVsibilityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UpdateAppserviceRoomDirectoryVsibilityOKBody update appservice room directory vsibility o k body
swagger:model UpdateAppserviceRoomDirectoryVsibilityOKBody
*/
type UpdateAppserviceRoomDirectoryVsibilityOKBody interface{}
