// Code generated by go-swagger; DO NOT EDIT.

package room_directory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/pkg/models"
)

// GetRoomIDByAliasReader is a Reader for the GetRoomIDByAlias structure.
type GetRoomIDByAliasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoomIDByAliasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRoomIDByAliasOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetRoomIDByAliasNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRoomIDByAliasOK creates a GetRoomIDByAliasOK with default headers values
func NewGetRoomIDByAliasOK() *GetRoomIDByAliasOK {
	return &GetRoomIDByAliasOK{}
}

/*GetRoomIDByAliasOK handles this case with default header values.

The room ID and other information for this alias.
*/
type GetRoomIDByAliasOK struct {
	Payload *models.GetRoomIDByAliasOKBody
}

func (o *GetRoomIDByAliasOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/directory/room/{roomAlias}][%d] getRoomIdByAliasOK  %+v", 200, o.Payload)
}

func (o *GetRoomIDByAliasOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetRoomIDByAliasOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoomIDByAliasNotFound creates a GetRoomIDByAliasNotFound with default headers values
func NewGetRoomIDByAliasNotFound() *GetRoomIDByAliasNotFound {
	return &GetRoomIDByAliasNotFound{}
}

/*GetRoomIDByAliasNotFound handles this case with default header values.

There is no mapped room ID for this room alias.
*/
type GetRoomIDByAliasNotFound struct {
	Payload *models.GetRoomIDByAliasNotFoundBody
}

func (o *GetRoomIDByAliasNotFound) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/directory/room/{roomAlias}][%d] getRoomIdByAliasNotFound  %+v", 404, o.Payload)
}

func (o *GetRoomIDByAliasNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetRoomIDByAliasNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
