// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/justinbarrick/go-matrix/models"
)

// GetTokenOwnerReader is a Reader for the GetTokenOwner structure.
type GetTokenOwnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokenOwnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTokenOwnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTokenOwnerOK creates a GetTokenOwnerOK with default headers values
func NewGetTokenOwnerOK() *GetTokenOwnerOK {
	return &GetTokenOwnerOK{}
}

/*GetTokenOwnerOK handles this case with default header values.

The token belongs to a known user.
*/
type GetTokenOwnerOK struct {
	Payload *models.GetTokenOwnerOKBody
}

func (o *GetTokenOwnerOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/r0/account/whoami][%d] getTokenOwnerOK  %+v", 200, o.Payload)
}

func (o *GetTokenOwnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetTokenOwnerOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
