// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SetAccountDataReader is a Reader for the SetAccountData structure.
type SetAccountDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetAccountDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetAccountDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetAccountDataOK creates a SetAccountDataOK with default headers values
func NewSetAccountDataOK() *SetAccountDataOK {
	return &SetAccountDataOK{}
}

/*SetAccountDataOK handles this case with default header values.

The account_data was successfully added.
*/
type SetAccountDataOK struct {
}

func (o *SetAccountDataOK) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/r0/user/{userId}/account_data/{type}][%d] setAccountDataOK ", 200)
}

func (o *SetAccountDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
