// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeactivateAccountUnauthorizedBodyFlowsItems deactivate account unauthorized body flows items
// swagger:model deactivateAccountUnauthorizedBodyFlowsItems
type DeactivateAccountUnauthorizedBodyFlowsItems struct {

	// The login type of each of the stages required to complete this
	// authentication flow
	// Required: true
	Stages []string `json:"stages"`
}

// Validate validates this deactivate account unauthorized body flows items
func (m *DeactivateAccountUnauthorizedBodyFlowsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeactivateAccountUnauthorizedBodyFlowsItems) validateStages(formats strfmt.Registry) error {

	if err := validate.Required("stages", "body", m.Stages); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeactivateAccountUnauthorizedBodyFlowsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeactivateAccountUnauthorizedBodyFlowsItems) UnmarshalBinary(b []byte) error {
	var res DeactivateAccountUnauthorizedBodyFlowsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
