// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DefineFilterParamsBodyAllOf0RoomEphemeral The events that aren't recorded in the room history, e.g. typing and receipts, to include for rooms.
// swagger:model defineFilterParamsBodyAllOf0RoomEphemeral
type DefineFilterParamsBodyAllOf0RoomEphemeral struct {
	DefineFilterParamsBodyAllOf0RoomEphemeralAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *DefineFilterParamsBodyAllOf0RoomEphemeral) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 DefineFilterParamsBodyAllOf0RoomEphemeralAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.DefineFilterParamsBodyAllOf0RoomEphemeralAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m DefineFilterParamsBodyAllOf0RoomEphemeral) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.DefineFilterParamsBodyAllOf0RoomEphemeralAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this define filter params body all of0 room ephemeral
func (m *DefineFilterParamsBodyAllOf0RoomEphemeral) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DefineFilterParamsBodyAllOf0RoomEphemeralAllOf0
	if err := m.DefineFilterParamsBodyAllOf0RoomEphemeralAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DefineFilterParamsBodyAllOf0RoomEphemeral) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefineFilterParamsBodyAllOf0RoomEphemeral) UnmarshalBinary(b []byte) error {
	var res DefineFilterParamsBodyAllOf0RoomEphemeral
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
