// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetEventsOKBodyChunkItems Event
// swagger:model getEventsOKBodyChunkItems
type GetEventsOKBodyChunkItems struct {
	GetEventsOKBodyChunkItemsAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *GetEventsOKBodyChunkItems) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 GetEventsOKBodyChunkItemsAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.GetEventsOKBodyChunkItemsAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m GetEventsOKBodyChunkItems) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.GetEventsOKBodyChunkItemsAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get events o k body chunk items
func (m *GetEventsOKBodyChunkItems) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with GetEventsOKBodyChunkItemsAllOf0
	if err := m.GetEventsOKBodyChunkItemsAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetEventsOKBodyChunkItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetEventsOKBodyChunkItems) UnmarshalBinary(b []byte) error {
	var res GetEventsOKBodyChunkItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
