// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetAvatarURLOKBody get avatar Url o k body
// swagger:model getAvatarUrlOKBody
type GetAvatarURLOKBody struct {

	// The user's avatar URL if they have set one, otherwise not present.
	AvatarURL string `json:"avatar_url,omitempty"`
}

// Validate validates this get avatar Url o k body
func (m *GetAvatarURLOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAvatarURLOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAvatarURLOKBody) UnmarshalBinary(b []byte) error {
	var res GetAvatarURLOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
