// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetTurnServerOKBody get turn server o k body
// swagger:model getTurnServerOKBody
type GetTurnServerOKBody struct {

	// The password to use.
	// Required: true
	Password *string `json:"password"`

	// The time-to-live in seconds
	// Required: true
	TTL *int64 `json:"ttl"`

	// A list of TURN URIs
	// Required: true
	Uris []string `json:"uris"`

	// The username to use.
	// Required: true
	Username *string `json:"username"`
}

// Validate validates this get turn server o k body
func (m *GetTurnServerOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTTL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUris(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetTurnServerOKBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *GetTurnServerOKBody) validateTTL(formats strfmt.Registry) error {

	if err := validate.Required("ttl", "body", m.TTL); err != nil {
		return err
	}

	return nil
}

func (m *GetTurnServerOKBody) validateUris(formats strfmt.Registry) error {

	if err := validate.Required("uris", "body", m.Uris); err != nil {
		return err
	}

	return nil
}

func (m *GetTurnServerOKBody) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetTurnServerOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetTurnServerOKBody) UnmarshalBinary(b []byte) error {
	var res GetTurnServerOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
