// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ModifyPresenceListParamsBody modify presence list params body
// swagger:model modifyPresenceListParamsBody
type ModifyPresenceListParamsBody struct {

	// A list of user IDs to remove from the list.
	Drop []string `json:"drop"`

	// A list of user IDs to add to the list.
	Invite []string `json:"invite"`
}

// Validate validates this modify presence list params body
func (m *ModifyPresenceListParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModifyPresenceListParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModifyPresenceListParamsBody) UnmarshalBinary(b []byte) error {
	var res ModifyPresenceListParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
