// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RedactEventOKBody redact event o k body
// swagger:model redactEventOKBody
type RedactEventOKBody struct {

	// A unique identifier for the event.
	EventID string `json:"event_id,omitempty"`
}

// Validate validates this redact event o k body
func (m *RedactEventOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RedactEventOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RedactEventOKBody) UnmarshalBinary(b []byte) error {
	var res RedactEventOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
