// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RegisterParamsBody register params body
// swagger:model registerParamsBody
type RegisterParamsBody struct {

	// auth
	Auth *RegisterParamsBodyAuth `json:"auth,omitempty"`

	// If true, the server binds the email used for authentication to
	// the Matrix ID with the ID Server.
	BindEmail bool `json:"bind_email,omitempty"`

	// ID of the client device. If this does not correspond to a
	// known client device, a new device will be created. The server
	// will auto-generate a device_id if this is not specified.
	DeviceID string `json:"device_id,omitempty"`

	// A display name to assign to the newly-created device. Ignored
	// if ``device_id`` corresponds to a known device.
	InitialDeviceDisplayName string `json:"initial_device_display_name,omitempty"`

	// The desired password for the account.
	Password string `json:"password,omitempty"`

	// The basis for the localpart of the desired Matrix ID. If omitted,
	// the homeserver MUST generate a Matrix ID local part.
	Username string `json:"username,omitempty"`
}

// Validate validates this register params body
func (m *RegisterParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuth(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterParamsBody) validateAuth(formats strfmt.Registry) error {

	if swag.IsZero(m.Auth) { // not required
		return nil
	}

	if m.Auth != nil {
		if err := m.Auth.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("auth")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RegisterParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterParamsBody) UnmarshalBinary(b []byte) error {
	var res RegisterParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
