// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RoomInitialSyncOKBody RoomInfo
// swagger:model roomInitialSyncOKBody
type RoomInitialSyncOKBody struct {

	// The private data that this user has attached to this room.
	AccountData []*RoomInitialSyncOKBodyAccountDataItems `json:"account_data"`

	// The user's membership state in this room.
	// Enum: [invite join leave ban]
	Membership string `json:"membership,omitempty"`

	// messages
	Messages *RoomInitialSyncOKBodyMessages `json:"messages,omitempty"`

	// The ID of this room.
	// Required: true
	RoomID *string `json:"room_id"`

	// If the user is a member of the room this will be the
	// current state of the room as a list of events. If the
	// user has left the room this will be the state of the
	// room when they left it.
	State []*RoomInitialSyncOKBodyStateItems `json:"state"`

	// Whether this room is visible to the ``/publicRooms`` API
	// or not."
	// Enum: [private public]
	Visibility string `json:"visibility,omitempty"`
}

// Validate validates this room initial sync o k body
func (m *RoomInitialSyncOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMembership(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoomID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisibility(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoomInitialSyncOKBody) validateAccountData(formats strfmt.Registry) error {

	if swag.IsZero(m.AccountData) { // not required
		return nil
	}

	for i := 0; i < len(m.AccountData); i++ {
		if swag.IsZero(m.AccountData[i]) { // not required
			continue
		}

		if m.AccountData[i] != nil {
			if err := m.AccountData[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("account_data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var roomInitialSyncOKBodyTypeMembershipPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["invite","join","leave","ban"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		roomInitialSyncOKBodyTypeMembershipPropEnum = append(roomInitialSyncOKBodyTypeMembershipPropEnum, v)
	}
}

const (

	// RoomInitialSyncOKBodyMembershipInvite captures enum value "invite"
	RoomInitialSyncOKBodyMembershipInvite string = "invite"

	// RoomInitialSyncOKBodyMembershipJoin captures enum value "join"
	RoomInitialSyncOKBodyMembershipJoin string = "join"

	// RoomInitialSyncOKBodyMembershipLeave captures enum value "leave"
	RoomInitialSyncOKBodyMembershipLeave string = "leave"

	// RoomInitialSyncOKBodyMembershipBan captures enum value "ban"
	RoomInitialSyncOKBodyMembershipBan string = "ban"
)

// prop value enum
func (m *RoomInitialSyncOKBody) validateMembershipEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, roomInitialSyncOKBodyTypeMembershipPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RoomInitialSyncOKBody) validateMembership(formats strfmt.Registry) error {

	if swag.IsZero(m.Membership) { // not required
		return nil
	}

	// value enum
	if err := m.validateMembershipEnum("membership", "body", m.Membership); err != nil {
		return err
	}

	return nil
}

func (m *RoomInitialSyncOKBody) validateMessages(formats strfmt.Registry) error {

	if swag.IsZero(m.Messages) { // not required
		return nil
	}

	if m.Messages != nil {
		if err := m.Messages.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("messages")
			}
			return err
		}
	}

	return nil
}

func (m *RoomInitialSyncOKBody) validateRoomID(formats strfmt.Registry) error {

	if err := validate.Required("room_id", "body", m.RoomID); err != nil {
		return err
	}

	return nil
}

func (m *RoomInitialSyncOKBody) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	for i := 0; i < len(m.State); i++ {
		if swag.IsZero(m.State[i]) { // not required
			continue
		}

		if m.State[i] != nil {
			if err := m.State[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("state" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var roomInitialSyncOKBodyTypeVisibilityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["private","public"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		roomInitialSyncOKBodyTypeVisibilityPropEnum = append(roomInitialSyncOKBodyTypeVisibilityPropEnum, v)
	}
}

const (

	// RoomInitialSyncOKBodyVisibilityPrivate captures enum value "private"
	RoomInitialSyncOKBodyVisibilityPrivate string = "private"

	// RoomInitialSyncOKBodyVisibilityPublic captures enum value "public"
	RoomInitialSyncOKBodyVisibilityPublic string = "public"
)

// prop value enum
func (m *RoomInitialSyncOKBody) validateVisibilityEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, roomInitialSyncOKBodyTypeVisibilityPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RoomInitialSyncOKBody) validateVisibility(formats strfmt.Registry) error {

	if swag.IsZero(m.Visibility) { // not required
		return nil
	}

	// value enum
	if err := m.validateVisibilityEnum("visibility", "body", m.Visibility); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RoomInitialSyncOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoomInitialSyncOKBody) UnmarshalBinary(b []byte) error {
	var res RoomInitialSyncOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
