// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SyncOKBodyRoomsInviteAdditionalPropertiesInviteState InviteState
//
// The state of a room that the user has been invited
// to. These state events may only have the ``sender``,
// ``type``, ``state_key`` and ``content`` keys
// present. These events do not replace any state that
// the client already has for the room, for example if
// the client has archived the room. Instead the
// client should keep two separate copies of the
// state: the one from the ``invite_state`` and one
// from the archived ``state``. If the client joins
// the room then the current state will be given as a
// delta against the archived ``state`` not the
// ``invite_state``.
// swagger:model syncOKBodyRoomsInviteAdditionalPropertiesInviteState
type SyncOKBodyRoomsInviteAdditionalPropertiesInviteState struct {
	SyncOKBodyRoomsInviteAdditionalPropertiesInviteStateAllOf0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SyncOKBodyRoomsInviteAdditionalPropertiesInviteState) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SyncOKBodyRoomsInviteAdditionalPropertiesInviteStateAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SyncOKBodyRoomsInviteAdditionalPropertiesInviteStateAllOf0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SyncOKBodyRoomsInviteAdditionalPropertiesInviteState) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.SyncOKBodyRoomsInviteAdditionalPropertiesInviteStateAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this sync o k body rooms invite additional properties invite state
func (m *SyncOKBodyRoomsInviteAdditionalPropertiesInviteState) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SyncOKBodyRoomsInviteAdditionalPropertiesInviteStateAllOf0
	if err := m.SyncOKBodyRoomsInviteAdditionalPropertiesInviteStateAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SyncOKBodyRoomsInviteAdditionalPropertiesInviteState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyncOKBodyRoomsInviteAdditionalPropertiesInviteState) UnmarshalBinary(b []byte) error {
	var res SyncOKBodyRoomsInviteAdditionalPropertiesInviteState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
