// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UploadContentOKBody upload content o k body
// swagger:model uploadContentOKBody
type UploadContentOKBody struct {

	// The MXC URI to the uploaded content.
	// Required: true
	ContentURI *string `json:"content_uri"`
}

// Validate validates this upload content o k body
func (m *UploadContentOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContentURI(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UploadContentOKBody) validateContentURI(formats strfmt.Registry) error {

	if err := validate.Required("content_uri", "body", m.ContentURI); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UploadContentOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadContentOKBody) UnmarshalBinary(b []byte) error {
	var res UploadContentOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
